webtalk_init -webtalk_dir C:/Users/zy/Desktop/Comple_Divide/Comple_Divide.sim/sim_1/behav/xsim/xsim.dir/Cordic_sim_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Jul 20 15:52:56 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "9cbe517e-7c9a-412c-920d-b5abb6347e3f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "8c49263e35e6487c8a3aac01b0276e36" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "111" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3292 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6784_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2117629789 -regid "" -xml C:/Users/zy/Desktop/Comple_Divide/Comple_Divide.sim/sim_1/behav/xsim/xsim.dir/Cordic_sim_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/zy/Desktop/Comple_Divide/Comple_Divide.sim/sim_1/behav/xsim/xsim.dir/Cordic_sim_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/zy/Desktop/Comple_Divide/Comple_Divide.sim/sim_1/behav/xsim/xsim.dir/Cordic_sim_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
